### ISSUE TITLE
Latest version of docker-ce requires containerd.io >= 1.4.1

### ISSUE THREAD

**Issue by FernandoMorais** [alvistack/ansible-role-docker#3]
Hi @hswong3i!

I'm working with your kubernetes collection (nice work) which depends on this docker role.

After some updates on docker it started to require containerd.io in newer versions.

This is the message my installation is trowing:
```
(item={'state': 'latest', 'name': 'docker-ce'}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "failures": [], "item": {"name": "docker-ce", "state": "latest"}, "msg": "Depsolve Error occured: \n Problem: package docker-ce-3:20.10.2-3.el7.x86_64 requires containerd.io >= 1.4.1, but none of the providers can be installed\n  - cannot install the best candidate for the job\n  - package containerd.io-1.4.3-3.1.el7.x86_64 is filtered out by modular filtering", "rc": 1, "results": []}
```

If you prefere I can do a PR here, and then you can propagate it till kubernetes collection.

**Comment by hswong3i** [comment]
Hi @FernandoMorais thank you very much for bug reporting, PR is always welcome ;-)

Anyway some more information is required:
  - Which OS, e.g. CentOS 8?
  - Which branch are you using, e.g. `develop`?
  - Error message seems like https://gitlab.com/alvistack/ansible-role-docker/-/jobs/968398979#L419?
  
In case if you could like to try for a PR (I could give a hand for you):
  - Setup you local testbed (I am using Ubuntu 20.04), following https://github.com/alvistack/ansible-role-docker/blob/develop/.gitlab-ci.yml as reference (P.S. tests are running with vagrant-libvirt, so inside a VM with CentOS/RHEL 8)
  - Update both the following files:
    - https://github.com/alvistack/ansible-role-docker/blob/develop/vars/centos-8.yml
    - https://github.com/alvistack/ansible-role-docker/blob/develop/vars/redhat-8.yml
  - Run the test with `source ./scripts/run-tests.sh && molecule test -s centos-8`
  - Create PR via `develop` branch

**Comment by hswong3i** [comment]
@FernandoMorais Umm... Not such simple... Docker CE finally support CentOS 8 officially, so changes goes more complicated, see https://github.com/alvistack/ansible-role-docker/commit/bc775394edb821ee7f3650f4e4459199f245f17b

**Comment by FernandoMorais** [comment]
Hi @hswong3i!

I think working with main branch...
I use CentOS 8 for my environment!
Yes! The message is the same of L419! :)

I'll PR the solution I did to keep working and that makes things going ok.

Regards,
Fernando

**Comment by FernandoMorais** [comment]
In time... I saw [bc77539](https://github.com/alvistack/ansible-role-docker/commit/bc775394edb821ee7f3650f4e4459199f245f17b) and agreed that this is the best solution, much more complete! :)

With that I wont create a PR, cause mine is less complete. :)
